# Generated by Django 6.0.4 on 2026-04-22 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść')),
                ('color', models.CharField(choices=[('#6c5ce7', 'Fioletowy'), ('#00b894', 'Zielony'), ('#fdcb6e', 'Żółty'), ('#e17055', 'Pomarańczowy'), ('#0984e3', 'Niebieski'), ('#d63031', 'Czerwony')], default='#6c5ce7', max_length=7, verbose_name='Kolor')),
                ('pinned', models.BooleanField(default=False, verbose_name='Przypięta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notatka',
                'verbose_name_plural': 'Notatki',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')], default='medium', max_length=10, verbose_name='Priorytet')),
                ('status', models.CharField(choices=[('todo', 'Do zrobienia'), ('in_progress', 'W trakcie'), ('done', 'Zrobione')], default='todo', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Termin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ['-created_at'],
            },
        ),
    ]
